# Generated by Django 5.2.4 on 2025-07-26 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('humidity_min', models.FloatField()),
                ('humidity_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('img_url', models.URLField(blank=True, null=True)),
                ('watering_freq', models.IntegerField(help_text='Frecuencia en días')),
                ('harvest_duration', models.IntegerField(help_text='Duración en días')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Cultivo')),
                ('init_date', models.DateField(verbose_name='Fecha de inicio')),
                ('last_watering', models.DateField(blank=True, null=True, verbose_name='Ultimo riego')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='plantium.plant', verbose_name='Planta')),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
    ]
